mysite/User/urls.py
from django.urls import path
from . import views

app_name = 'User'
urlpatterns = [
    path('', views.index, name='home'),
    path('login', views.Login.as_view(), name='login'),
    path('logout', views.Logout.as_view(), name='logout'),
    path('register', views.Register.as_view(), name='register'),
    path('success_saved', views.success_saved, name='success_saved')
]

mysite/blogs/urls.py
from django.urls import path
from . import views
app_name = 'blogs'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:Blog_id>/', views.detail, name='detail'),
    path('create', views.create, name='create'),
    path('success_saved', views.success_saved, name='success_saved'),
    path('<int:Blog_id>/update', views.Update.as_view(), name='update'),
    path('<int:Blog_id>/delete', views.Delete.as_view(), name='delete'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('main', include('main.urls'), name='home'),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls'), name='polls'),
    path('blogs/', include('blogs.urls'), name='blogs'),
    path('', include('User.urls'), name='User'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/blogs/models.py
from django.utils import timezone
import datetime
from django.db import models


class Blog(models.Model):
    DoesNotExist = None
    title = models.CharField(max_length=200)
    task = models.TextField()
    pub_date = models.DateTimeField(default=timezone.now(), verbose_name="Time published")
    cover = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f'/blogs/{self.id}'

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

mysite/blogs/forms.py
from django.forms import ModelForm, TextInput, Textarea, DateTimeField
from .models import Blog


class CreateForm(ModelForm):
   class Meta:
       model = Blog
       fields = ['title', 'task', 'pub_date', 'cover']

       widgets = {
           "title": TextInput(attrs={
               'class': 'form-control',
               'placeholder': 'Название блога'
           }),
           'task': Textarea(attrs={
               'class': 'form-control',
               'placeholder': 'Текст блог'
           }),

    }

mysite/blogs/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from django.views.generic import UpdateView, DeleteView

from .forms import CreateForm
from .models import Blog


def index(request):
    latest_blog_list = Blog.objects.order_by('-pub_date')[:10]
    template = loader.get_template('blogs/index.html')
    context = {
        'latest_blog_list': latest_blog_list,
    }
    return render(request, 'blogs/index.html', context)

def detail(request, Blog_id):
    try:
        blog = Blog.objects.get(pk=Blog_id)
    except Blog.DoesNotExist:
        raise Http404("Blog does not exist")
    return render(request, 'blogs/detail.html', {'blog': blog})


def create(request):
    error =''
    if request.method == 'POST':
        form = CreateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('blogs:success_saved'))
        else:
            error = 'Неправмльная форма'

    form = CreateForm()
    data = {
        'form': form,
        'error': error
    }
    return render(request, 'blogs/create.html', data)


def success_saved(request):
    return render(request, 'blogs/success_saved.html')


class Update(UpdateView):
    model = Blog
    pk_url_kwarg = "Blog_id"
    success_url = '/blogs/'
    template_name = 'blogs/update.html'
    form_class = CreateForm


class Delete(DeleteView):
    model = Blog
    pk_url_kwarg = "Blog_id"
    success_url = '/blogs/'
    template_name = 'blogs/delete.html'

mysite/blogs/templates/blogs/create.html
{% extends 'polls/layout.html' %}
{% block title %}Создание Блога{% endblock %}
{% block content %}
<style>
   BODY
   {
    background-blend-mode: screen;
	background:
		linear-gradient(limegreen, transparent),
		linear-gradient(90deg, skyblue, transparent),
		linear-gradient(-90deg, coral, transparent);
   }
  </style>
<div class="features">
    <h1>
        Создание Блога
    </h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.title }}<br>
        {{ form.task }}<br>
        {{ form.cover }}<br><br>
        {{ form.pub_date }}<br><br>
        <span>{{ error }}</span>
        <button class="btn btn-success" type="submit">Добавить блог</button>
    </form>
</div>
{% endblock %}

mysite/blogs/templates/blogs/delete.html
{% extends 'polls/layout.html' %}
{% block title %}Создание Блога{% endblock %}
{% block content %}
<style>
   BODY
   {
    background-blend-mode: screen;
	background:
		linear-gradient(limegreen, transparent),
		linear-gradient(90deg, skyblue, transparent),
		linear-gradient(-90deg, coral, transparent);
   }
  </style>
<div class="features">
    <h1>
        Удаление блога<br>
        Хотите удалить этот блог?
    </h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">Удалить блог</button>
        <button class="btn btn-warning" type="submit">Нет, не хочу, но но все равно удалить</button>
    </form>
</div>
{% endblock %}

mysite/blogs/templates/blogs/detail.html
{% extends 'polls/layout.html' %}

{% block content %}
        <style>
        BODY
        {
        background-blend-mode: screen;
	    background:
		linear-gradient(limegreen, transparent),
		linear-gradient(90deg, skyblue, transparent),
		linear-gradient(-90deg, coral, transparent);
		}
           figure
           {
                height: 595px;
                margin: 0;
                overflow: hidden;
           }
           figure img
           {
                width: 100%;
                margin: -10% 0 0 0;
           #glaw
           {
               display:inline;
               width:880px;
           }

           .blok1 {
              float:left;
              width:600px;
              height:660px;
              padding: 5px;
              text-align: center;
              vertical-align: middle;
          }
          .blok2 {
              vertical-align: middle;
              float:right;
              width:600px;
              height:660px;
              padding: 5px;
              text-align: center;
          }
        </style>
                {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <div id="glaw">
            <div class="blok1">
                <h1>
                    <p align="center" style="color:#DC143C; font-size:30px">
                    {{ blog.title }}
                </h1>
                    <div align="right">
                    <figure>
                        <p vertical-align="middle"></p>
                        <img src="{{ blog.cover.url }}">
                    </figure>
                    </div>
            </div>
            <div class="blok2">
                    <div align="left" style="color:black; font-size:20px">
                        {{ blog.task }}
                    </div>
                    <p align="right" style="color:#DC143C; font-size:20px">
                    Опубликован: {{ blog.pub_date }}
            </div>
            <br>
                <h3>
                    <p align="center" style="margin-top: 640px">
                    <button class="btn btn-info" style="width:350px" onclick="document.location='../'"><---Назад к списку</button>
                    <button class="btn btn-warning" style="width:350px" onclick="document.location='update'">Редактировать блог</button>
                    <button class="btn btn-danger" style="width:350px" onclick="document.location='delete'">Удалить блог</button>
                </h3>
        </div>
{% endblock %}

mysite/blogs/templates/blogs/index.html
{% extends 'polls/layout.html' %}

{% block content %}
<style>
   BODY
   {
    background-blend-mode: screen;
	background:
		linear-gradient(limegreen, transparent),
		linear-gradient(90deg, skyblue, transparent),
		linear-gradient(-90deg, coral, transparent);
   }
  </style>
<div class="INDEX">
     <h1>
        <p align="center" style="color:#DC143C; font-size:35px">
        Список блогов
    </h1>
     <h2>
        {% if latest_blog_list %}
            <ul>
            {% for blog in latest_blog_list %}
               <p align="left" style="color:#DC143C; font-size:35px">
               <p><li><a href="{% url 'blogs:detail' blog.id %}">{{ blog.title }}<br></a></li></p>
            {% endfor %}
            </ul>
        {% else %}
             <p>Нет созданных блогов.</p>
        {% endif %}
     </h2>
    <h4>
<button class="btn btn-success" onclick="document.location='create'">Создать блог</button>
    </h4>
    <h5>
            <p style="margin-top:200px">

        </h5>
</div>

{% endblock %}

mysite/blogs/templates/blogs/success_saved.html
{% extends 'polls/layout.html' %}

{% block content %}
<style>
   BODY
   {
    background-blend-mode: screen;
	background:
		linear-gradient(limegreen, transparent),
		linear-gradient(90deg, skyblue, transparent),
		linear-gradient(-90deg, coral, transparent);
   }
  </style>
<div class="features">
    <h1>
        Блог был успешно сохранён.<br>

    </h1>
    <h2>
        <button class="btn btn-outline-warning" style="height:50px;width:200px"
                onclick="document.location='../blogs/'">Назад к блогам</button>
    </h2>
   </div>
{% endblock %}

mysite/blogs/templates/blogs/update.html
{% extends 'polls/layout.html' %}
{% block title %}Создание Блога{% endblock %}
{% block content %}
<style>
   BODY
   {
    background-blend-mode: screen;
	background:
		linear-gradient(limegreen, transparent),
		linear-gradient(90deg, skyblue, transparent),
		linear-gradient(-90deg, coral, transparent);
   }
  </style>
<div class="features">
    <h1>
        Редактирование Блога
    </h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.title }}<br>
        {{ form.task }}<br>
        {{ form.cover }}<br><br>
        {{ form.pub_date }}<br><br>
        <span>{{ error }}</span>
        <button class="btn btn-success" onclick="document.location='../'" type="submit">Изменить блог</button>
    </form>
</div>
{% endblock %}